<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZwabg1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZwabg1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZwabg1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZwabg1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZwabg1\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZwabg1',
    'container.build_id' => '99c2f1db',
    'container.build_time' => 1630511700,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZwabg1');
