<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6Ask9xI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6Ask9xI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6Ask9xI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6Ask9xI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6Ask9xI\App_KernelDevDebugContainer([
    'container.build_hash' => '6Ask9xI',
    'container.build_id' => 'e9869a29',
    'container.build_time' => 1628860093,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6Ask9xI');
