<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNqe7mB3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNqe7mB3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNqe7mB3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNqe7mB3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNqe7mB3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nqe7mB3',
    'container.build_id' => '9af3845d',
    'container.build_time' => 1628456221,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNqe7mB3');
